# Generated by Django 5.0.1 on 2024-02-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image_uploder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/image')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
