# Generated by Django 5.0.1 on 2024-02-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_uploder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_uploder',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
